<?php $this->layout('../template', ['menu' => $menu, 'sessao' => $sessao]) ?>
<h1>Novo Usuário</h1>
<form action="/aplicacao/usuarios/add/salvar" method="post" id="frmModulos" class="form-horizontal form-label-left" novalidate>
    <?php
    /**
     * @var \Aplicacao\Entity\SistemaUsuarios $usuario
     */
    ?>
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="modulo">Usuário <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" name="usuario" id="usuario" class="form-control col-md-7 col-xs-12" value="" required="required">
        </div>
    </div>
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="menu">Senha <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" name="senha" id="senha" class="form-control col-md-7 col-xs-12" value="" required="required">
        </div>
    </div>
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="href">E-mail <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="email" name="email" id="email" class="form-control col-md-7 col-xs-12" value="" required="required">
        </div>
    </div>
    <div class="ln_solid"></div>
    <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
            <a href="/aplicacao/usuarios" type="button" class="btn btn-primary" id="cancelar">Canelar</a>
            <button type="submit" class="btn btn-success" id="enviar">Salvar</button>
        </div>
    </div>
</form>