<?php $this->layout('../template', ['menu' => $menu, 'sessao' => $sessao]) ?>
<h1>Editar Usuário</h1>
<?php if (isset($msgError) && !empty($msgError)): ?>
    <div class="alert alert-danger">
        <a href="javascript:;" class="close">&times;</a>
        <?= $msgError; ?>
    </div>
<?php endif; ?>
<form action="/aplicacao/usuarios/password/<?= $usuario->getIdUsuarios() ?>/salvar" method="post" id="frmModulos"
      class="form-horizontal form-label-left" novalidate>
    <?php
    /**
     * @var \Aplicacao\Entity\SistemaUsuarios $usuario
     */
    ?>
    <input type="hidden" name="idUsuarios" id="idUsuarios" value="<?= $usuario->getIdUsuarios() ?>">
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="menu">Senha Usuario Logado</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="password" name="senhalogado" id="senhalogado" class="form-control" value=""
                   required="required" class="form-control col-md-7 col-xs-12">
        </div>
    </div>
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="menu">Nova Senha</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" name="senha" id="senha" class="form-control" value=""
                   class="form-control col-md-7 col-xs-12" required="required">
        </div>
    </div>
    <div class="ln_solid"></div>
    <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
            <a href="/aplicacao/usuarios" type="button" class="btn btn-primary" id="cancelar">Canelar</a>
            <button type="submit" class="btn btn-success" id="enviar">Salvar</button>
        </div>
    </div>
</form>
<script type="text/javascript" src="/public/vendors/validator/validator.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.close').click(function () {
            $(this).parent().hide();
        })
    })
</script>