<?php $this->layout('../template', ['menu'=>$menu, 'sessao'=>$sessao]) ?>
<h1>Listagem de Modulos</h1>
<p>
    <a href="/aplicacao/modulos/add" class="btn btn-default">Novo Menu</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>Modulo</th>
        <th>Menu</th>
        <th>Href</th>
        <th>Exibir</th>
        <th>Ordem</th>
        <th>Ações</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($dados as $dado): ?>
        <?php
        /**
         * @var \Aplicacao\Entity\SistemaModulos $dado
         */
        ?>
    <tr>
        <td><?= $dado->getIdModulos() ?></td>
        <td><?= $dado->getModulo() ?></td>
        <td><?= $dado->getMenu() ?></td>
        <td><?= $dado->getHref() ?></td>
        <td>
            <?php if($dado->isExibir()): ?>
                Sim
            <?php else: ?>
                Não
            <?php endif; ?>
        </td>
        <td><?= $dado->getOrdem() ?></td>
        <td>
            <a href="/aplicacao/modulos/edit/<?= $dado->getIdModulos() ?>"><i class="fa fa-pencil"></i></a>
            <a href="/aplicacao/modulos/delete/<?= $dado->getIdModulos() ?>" class="deletar"><i class="fa fa-trash"></i></a>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function(){
        $('.deletar').click(function() {
            if(!confirm('Você tem certez que vai deletar esse menu')){
               return false;
            }
            return true;
        });
    });
</script>
